### ISSUE TITLE
server_nameが正しく判別できていない問題

### ISSUE THREAD

**Issue by welove-t** [ichinose9372/42-webserv#108]

**Comment by snemoto-42** [comment]
- [ ]  初回実行時に405 Method Not Allowed、8081番のポートでmethodを指定する
- [ ]  /docs2/を指定していた、virtual.htmlが表示されない
- [ ]

**Comment by snemoto-42** [comment]
・default_serverの8081番ポートの実行後に8080番を実行すると、8081番のHTMLが表示される
・Host:  virtual_serverの場合に、default_server用のHTMLが表示される（解決後にdebugコメントアウトを削除）
・googleTestを追加

**Comment by snemoto-42** [comment]
別issueを作成済み
