### ISSUE TITLE
autoindexを任意で設定できるように対応

### ISSUE THREAD

**Issue by welove-t** [ichinose9372/42-webserv#111]
現状はrootディレクトリのみ出力される仕様。
これを任意のディレクトリを指定できるように変更する

**Comment by snemoto-42** [comment]
autoindex onの場合、その配下のディレクトリを表示（autoindexの仕様を確認）

**Comment by snemoto-42** [comment]
ディレクトリ リスティングがONの時
・indexに指定されたファイルを返す
・指定されたファイルがない場合にはディレクトリの中身一覧を返す

ディレクトリ リスティングがOFFの時
・indexに指定されたファイルを返す
・指定されたファイルがない場合には403エラー（権限が無効です）を返す

**Comment by snemoto-42** [comment]
ディレクトリ リスティングがONの時
・indexに指定されたファイルを返す
・指定されたファイルがない場合にはディレクトリの中身一覧を返す

ディレクトリ リスティングがOFFの時
・indexに指定されたファイルを返す
・指定されたファイルがない場合には403エラー（権限が無効です）を返す
