### ISSUE TITLE
macOS以外でも実行可能であるかのテストが必要

### ISSUE THREAD

**Issue by snemoto-42** [ichinose9372/42-webserv#139]
googleTestの設定を変えれば簡単に確認できそう

**Comment by ichinose9372** [comment]
actionで確認するのは効率が悪いのでdockerを導入
環境を作成して、ローカルのディレクトリをコンテナの中にマウントしすぐにコンパイルができる環境を設定
コンパイルエラーをすぐに確認できます。
dockerは素のubuntuの環境に必要なものをインストールした段階で
docker commit コマンドでimageを作成できる。
そのimageを使用して次からコンテナを起動できる。
