### ISSUE TITLE
errnoを削除（socket系）

### ISSUE THREAD

**Issue by welove-t** [ichinose9372/42-webserv#65]

**Comment by snemoto-42** [comment]
soketシステムコールにおいてerrnoを使わないようにする
→関数の返値0or-1のみハンドリングする
→クライアントを削除する（yichinoseさんと連携）

**Comment by snemoto-42** [comment]
Check the code and ask questions
・Search for all read/recv/write/send and check if the returned value is correctly checked (checking only -1 or 0 values is not enough, both should be checked).
・If errno is checked after read/recv/write/send, the grade is 0 and the evaluation process ends now.
