### ISSUE TITLE
autoindex対応

### ISSUE THREAD

**Issue by welove-t** [ichinose9372/42-webserv#69]

**Comment by snemoto-42** [comment]
・autoindexはディレクトリの状況を読み込んで動的に表示
・各ページがクリックされたら、当該ページの内容を表示
・default.cnfに/docs/を追加するか

**Comment by snemoto-42** [comment]
概要
https://qiita.com/U_mfunyu/items/dc4d76603a8e8f36ed92
Flaskでの実装
https://github.com/general03/flask-autoindex/blob/master/flask_autoindex/templates/__autoindex__/autoindex.html

**Comment by snemoto-42** [comment]
Check with a browser
・Try to list a directory.

**Comment by snemoto-42** [comment]
TODO
・files,directoriesをHTMLにレンダリングする方法（flaskやDjangoのようなフレームワークを使わないで）

**Comment by snemoto-42** [comment]
TODO
・Request.cppなどの修正が必要
・CGIと同じようにexecve()からapp.pyを呼び出す必要がある
