### ISSUE TITLE
レビュー用シェルスクリプト作成

### ISSUE THREAD

**Issue by welove-t** [ichinose9372/42-webserv#70]

**Comment by snemoto-42** [comment]
・googleTestの更新
・無限ループ.shスクリプト
・URLの内容（パラメータなど）を表示するCGIスクリプト

**Comment by snemoto-42** [comment]
Configuration
・Search for the HTTP response status codes list on the internet. During this evaluation, if any status codes is wrong, don't give any related points.
・Setup multiple servers with different ports.
・Setup multiple servers with different hostnames (use something like: curl --resolve example.com:80:127.0.0.1 http://example.com/ (http://example.com/)).
・Setup default error page (try to change the error 404).
・Limit the client body (use: curl -X POST -H "Content-Type: plain/text" --data "BODY IS HERE write something shorter or longer than body limit").
・Setup routes in a server to different directories.
・Setup a default file to search for if you ask for a directory.
・Setup a list of methods accepted for a certain route (e.g., try to delete something with and without permission).

**Comment by snemoto-42** [comment]
Basic checks
Using telnet, curl, prepared files, demonstrate that the following features work properly:
・GET, POST and DELETE requests should work.
・UNKNOWN requests should not result in a crash.
・For every test you should receive the appropriate status code.
・Upload some file to the server and get it back.

**Comment by snemoto-42** [comment]
#82 
バグは修正されたため、残りのPython周りのTODOは下記
・/autoindex/のgetcwd()を修正、絶対パスを指定して/docs/傘下のファイルを表示
・autoindex.htmlの{{ path }}を修正
・flaskで/python/のルーティング

**Comment by snemoto-42** [comment]
python周りのTODOは別issueに分けました
