### ISSUE TITLE
初回実行時の405 Method Not Allowedエラー

### ISSUE THREAD

**Issue by welove-t** [ichinose9372/42-webserv#74]

**Comment by snemoto-42** [comment]
もう発生していないような気がしてます

**Comment by snemoto-42** [comment]
curl --resolve default_server:8081:0.0.0.0 http://default_server:8081
curl --resolve virtual_server:8081:0.0.0.0 http://virtual_server:8081
で発生

**Comment by snemoto-42** [comment]
8081番のポートでmethodを指定すると解決
